export const ASSETS = {
  defaultGlobalImage: 'https://res.cloudinary.com/daoawcamj/image/upload/v1707597685/actmttfunk4v17mk6664.png',
  favGreen: '/fav/favGreen.svg',
  favWhite: '/fav/favWhite.svg',
  favBlack: '/fav/favBlack.svg',
  favGrey: '/fav/favGrey.svg',
  logoGreen: '/images/logoGreen.svg',
  logoWhite: '/images/logoWhite.svg',
  logoBlack: '/images/logoBlack.svg',
  theLines: '/images/TheLines.svg',
  heroImage: '/images/hero.svg',
  heroImageHalf1: '/images/heroHalf1.svg',
  heroImageHalf2: '/images/heroHalf2.svg',
  craft: '/images/craft.svg',
  track: '/images/track.svg',
  createImage: '/images/create.svg',
  publicViewDark: '/images/view.svg',
  publicViewLight: '/images/publicViewLight.svg',
  close: '/images/close.svg',
  expand: '/images/expand.svg',
};
